<?php
/**
 * Created by PhpStorm.
 * User: caipeichao
 * Date: 14-3-11
 * Time: PM5:41
 */

namespace Admin\Controller;

use Admin\Builder\AdminConfigBuilder;
use Admin\Builder\AdminListBuilder;
use Admin\Builder\AdminTreeListBuilder;


class HdygController extends AdminController
{
    protected $issueModel;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function index($page = 1, $r = 10)
    {
        $this->redirect("whtyhd");
    }

    /**
     * 文体活动
     * @param int $page
     * @param int $r
     */
    public function whtyhd($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }

        //读取列表
        $map['status'] = array('neq', "-1");
        $map['type'] = 1;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
        }

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        $builder->title('文体活动')
            ->buttonNew(U('editWhtyhd'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyDoActionEdit('editWhtyhd?id=###')
             ->keyDoAction("bmlist?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    public function bmlist($page = 1, $r = 10)
    {
        $aid = I('aid', 0, 'intval');

        $kc = M('data_hdyg')->where(array("id" => $aid))->find();
        //读取列表
        $map['aid'] = $aid;
        $map['status'] = 1;
        $map['state'] = array("in" ,array(0,1));
        $model = M('data_hdbm');
        $list = $model->where($map)->page($page, $r)->order("starttime desc")->select();
        $totalCount = $model->where($map)->count();

        if($kc["type"] == 6){
            //$builder->keyText()
            foreach ($list as &$v){
                $v["yytime"]=date("Y-m-d H:i:s",$v["starttime"])."—".date("Y-m-d H:i:s",$v["endtime"]);
            }
        }
        unset($v);

        //显示页面
        $builder = new AdminListBuilder();
        $builder->title("\"" . $kc['name'] . "\"报名人员")
            ->keyText('name', '姓名')->keyText('mobile', '联系电话')->keyCreateTime('create_time', '创建时间');

        if($kc["type"] == 6){
            $builder->keyText("yytime","预约时间段");
            $builder->keyText("company","预约部门");
        }
        $builder->data($list)
        ->pagination($totalCount, $r)
        ->display();
    }

    public function bmlist2($page = 1, $r = 10)
    {
        $aid = I('aid', 0, 'intval');

        $kc = M('data_hdyg')->where(array("id" => $aid))->find();
        //读取列表
        $map['aid'] = $aid;
        $map['status'] = 1;
        $map['state'] = array("in" ,array(0,1,2));
        $model = M('data_hdbm');
        $list = $model->where($map)->page($page, $r)->order("starttime desc")->select();
        $totalCount = $model->where($map)->count();

        if($kc["type"] == 6){
            //$builder->keyText()
            foreach ($list as &$v){
                $v["yytime"]=date("Y-m-d H:i:s",$v["starttime"])."—".date("Y-m-d H:i:s",$v["endtime"]);
            }
        }
        unset($v);

        //显示页面
        $builder = new AdminListBuilder();
        $builder->title("\"" . $kc['name'] . "\"报名人员")
            ->keyText('name', '姓名')->keyText('mobile', '联系电话')->keyCreateTime('create_time', '创建时间');

        if($kc["type"] == 6){
            $builder->keyText("yytime","预约时间段");
            $builder->keyText("company","预约部门");
        }
        $builder->data($list)
            ->pagination($totalCount, $r)
            ->keyStatus('state')
//            ->buttonDisable(U('hdStatus',array('state'=>1)),L('_UNAUDITED_'))
            ->buttonDisable(U('hdStatus',array('state'=>1)),L('通过'))
            ->buttonDisable(U('hdStatus',array('state'=>0)),L('禁止'))
            ->buttonDisable(U('hdStatus',array('state'=>-1)),L('删除'))
            ->display();
    }
    /*
     * 活动报名管理*/
    public function hdStatus(){
        $ids = I('ids');
        $state = I('get.state', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetState('data_hdbm', $ids, $state);
    }
    public function setHdStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_hdyg', $ids, $status);

    }

    /**
     * 群团活动
     * @param int $page
     * @param int $r
     */
    public function qthd($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('neq',"-1");
        $map['type'] = 2;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();
        $qttypeopt = array("1"=>"工会","2"=>"妇联","3"=>"共青团");
        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['qttype']) {
                $v["qttype_str"] = $qttypeopt[$v['qttype']];
            }
        }
        unset($v);

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        $builder->title('群团活动')
            ->buttonNew(U('editQthd'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '标题')->keyText('qttype_str', '活动类型')->keyText('zb', '主办')->keyText('xb', "协办")->keyText('date', '时间')
            ->keyText('status_str', '状态')
            ->keyDoActionEdit('editQthd?id=###')
             ->keyDoAction("bmlist?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    /**
     * 红色电影
     * @param int $page
     * @param int $r
     */
    public function hsdy($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('neq',"-1");
        $map['type'] = 5;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }

        }

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        $builder->title('红色电影')
            ->buttonNew(U('editHsdy'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyDoActionEdit('editHsdy?id=###')
            ->keyDoAction("bmlist?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }
    /**
     * 编辑添加红色电影
     */
    public function editHsdy()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 5;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }
            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 5;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "红色电影")
                ->keyText('name', "活动主题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }


    /**
     * 场地预约
     * @param int $page
     * @param int $r
     */
    public function cdyy($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('neq',"-1");
        $map['type'] = 6;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->order("sort desc")->select();

        $totalCount = $model->where($map)->count();
        $subtypeopt = array( "1"=>"网页预约","2"=>"电话预约");
        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            $v["subtype_str"] = $subtypeopt[$v["subtype"]];
            $v['qrcode'] = 'http://hqdj.cmlzjz.com/home/index/qrcode/type/hdxq/id/'.$v['id'];
        }
        unset($v);
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        $builder->title('场地管理')
            ->buttonNew(U('editCdyy'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()   ->buttonNew(U('export',array('type'=>6)),'导出excel')
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyText('subtype_str', '预约方式')
            ->keyText('tel', '预约电话')
            ->keyImage('qrcode', '二维码', array("width" => 24, "height" => 24 ,"style"=>"border-radius:0;"))
            ->keyText('sort', '排序(越大越靠前)')
            ->keyDoActionEdit('editCdyy?id=###')
            ->keyDoAction("bmxx?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("sbgl?aid=###", "设备管理")
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }
    //导出Excel表格
    public function export($type,$title=array(1,2,3,4),$filename='report'){
        $data = array();
        $filename='未知';
        $beginThismonth=mktime(0,0,0,1,1,date('Y'));
        $endThismonth=mktime(23,59,59,12,31,date('Y'));
        $maps['create_time'] = array('elt', $endThismonth);
        $maps['create_time'] = array('egt',$beginThismonth);
        $beginThismonth2=mktime(0,0,0,1,1,date('Y')-1);
        $endThismonth2=mktime(23,59,59,12,31,date('Y')-1);
        $map2['create_time'] = array('elt', $endThismonth2);
        $map2['create_time'] = array('egt',$beginThismonth2);
        if($type == 6){         //场地
            $title = array('编号','场地名称','场地地址','总计报名',date('Y'),date('Y')-1);
            $filename = '场地预约表单';
            $map['status'] = 1;
            $map['type'] = $type;
            $model = M('data_hdyg');
            $data = $model->where($map)->field('id,name,addr')->order("sort desc")->select();
            $aid = null;
            foreach($data as $k=>$v){
                $data[$k]['Total'] =M('data_hdbm')->where(array('aid'=>$v['id']))->count();
                $maps['aid'] =$v['id']   ;
                $data[$k]['TotalNew'] =M('data_hdbm')->where($maps)->count();
                $map2['aid'] =$v['id']   ;
                $data[$k]['TotalLast'] =M('data_hdbm')->where($map2)->count();
            }
        }elseif($type == 1){                 //活动
            $title = array('编号','活动名称','活动地址','总计报名',date('Y'),date('Y')-1);
            $filename = '活动预约表单';
            $map['status'] = 1;
            $map['type'] = $type;
            $model = M('data_hdyg');
            $data = $model->where($map)->field('id,name,addr')->order("sort desc")->select();
            $aid = null;
            foreach($data as $k=>$v){
                $data[$k]['Total'] =M('data_hdbm')->where(array('aid'=>$v['id']))->count();
                $maps['aid'] =$v['id']   ;
                $data[$k]['TotalNew'] =M('data_hdbm')->where($maps)->count();
                $map2['aid'] =$v['id']   ;
                $data[$k]['TotalLast'] =M('data_hdbm')->where($map2)->count();
            }
        }elseif($type == 'dk'){
            $title = array('编号','课程名称','课程地址','讲师','总计报名',date('Y'),date('Y')-1);
            $filename = '党课预约表单';
            $map['status'] = 1;
            $model = M('apply_djkc');
            $data = $model->where($map)->field('id,course_name,addr,contacter')->order("id desc")->select();
            $aid = null;
            foreach($data as $k=>$v){
                $data[$k]['Total'] =M('data_dkbm')->where(array('aid'=>$v['id']))->count();
                $maps['aid'] =$v['id']   ;
                $data[$k]['TotalNew'] =M('data_dkbm')->where($maps)->count();
                $map2['aid'] =$v['id']   ;
                $data[$k]['TotalLast'] =M('data_dkbm')->where($map2)->count();
            }
        }else{
            exit;
        }

//        dump($data);
//      exit;
            header("Content-type:application/octet-stream");
            header("Accept-Ranges:bytes");
            header("Content-type:application/vnd.ms-excel");
            header("Content-Disposition:attachment;filename=".$filename.".xls");
            header("Pragma: no-cache");
            header("Expires: 0");
            if (!empty($title)){
                foreach ($title as $k => $v) {
                    $title[$k]=iconv("UTF-8", "GB2312",$v);
                }
                $title= implode("\t", $title);
                echo "$title\n";
            }
            if (!empty($data)){
                foreach($data as $key=>$val){
                    foreach ($val as $ck => $cv) {
                        $data[$key][$ck]=iconv("UTF-8", "GB2312", $cv);
                    }
                    $data[$key]=implode("\t", $data[$key]);

                }
                echo implode("\n",$data);
            }

    }

    public function sbgl($page=1,$r=10){

        $aid = I('aid', 0, 'intval');

        $kc = M('data_hdyg')->where(array("id" => $aid))->find();
        //读取列表
        $map['aid'] = $aid;
        $map['status'] = 1;
        $map['state'] = 1;
        $model = M('data_hdsb');
        $list = $model->where($map)->page($page, $r)->select();
        $totalCount = $model->where($map)->count();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
        $builder->title("\"" . $kc['name'] . "\"设备清单")
            ->buttonNew(U('editSb',array("aid"=>$aid)))
            ->setStatusUrl(U('setSbStatus'))->buttonDelete()
            ->keyText('name', '设备名称')->keyText("count", '数量')->keyText("pj", '配件')->keyText('bz', '使用说明');
        $builder->keyDoActionEdit("editSb?aid=".$aid."&id=###");
        $builder->data($list)
            ->pagination($totalCount, $r)
            ->display();

    }

    /**
     * 删除设备
     */
    public function setSbStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_hdsb', $ids, $status);
    }
    /**
     * 编辑设备
     */
    public function editSb()
    {
        $id = I('id');
        $aid = I('aid');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $m = M('data_hdsb');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdsb')->where($map)->find();
            }
            $data['aid'] = $aid;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "设备清单")
                ->keyText('name', "设备名称")
                ->keyText('count', "数量")
                ->keyText('pj', "配件")
                ->keyTextArea('bz', "使用说明")
                ->keyHidden("id","")
                ->keyHidden("aid","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /**
     * 编辑添加场地预约
     */
    public function editCdyy()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 6;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 6;
            $builder = new AdminConfigBuilder();

            $subtypeopt = array(""=>"---请选择---",  "1"=>"网页预约","2"=>"电话预约");

            $builder->title($title . "场地预约")
                ->keyText('name', "场地名称")
                ->keySelect("subtype","预约方式（决定微信页面显示预约按钮还是预约电话）","",$subtypeopt)
				->keySingleImage('pic1', "图片")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyText("sort", "排序(越大越靠前)")
                ->keyText("tel","预约电话")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }


    /**
     * 书记代教
     * @param int $page
     * @param int $r
     */
    public function sjdj($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('neq',"-1");
        $map['type'] = 4;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }

        }

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        $builder->title('书记代教')
            ->buttonNew(U('editHsdy'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyDoActionEdit('editHsdy?id=###')
            ->keyDoAction("bmlist?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }
    /**
     * 编辑添加书记代教
     */
    public function editSjdj()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 4;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 4;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "书记代教")
                ->keyText('name', "活动主题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }



    /**
     * 公益活动
     * @param int $page
     * @param int $r
     */
    public function gyhd($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('neq',"-1");
        $map['type'] = 3;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('公益活动')
            ->buttonNew(U('editGyhd'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyDoActionEdit('editGyhd?id=###')
            ->keyDoAction("bmlist?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function editGyhd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 3;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }

            $data['type'] = 3;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "公益活动")
                ->keyText('name', "标题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    /**
     * 编辑添加文化体育活动
     */
    public function editWhtyhd()
    {

        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 1;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }

            $data['type'] = 1;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "文体活动")
                ->keyText('name', "活动主题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    /**
     * 编辑添加群团活动
     */
    public function editQthd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 2;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            //1工会2妇联3共青团
            $data['type'] = 2;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "群团")
                ->keyText('name', "标题")
                ->keySelect('qttype', "群团活动类型","",array(""=>"---请选择---","1"=>"工会","2"=>"妇联","3"=>"共青团"))
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText('zb', "主办")
                ->keyText('xb', "协办")
                ->keyTextArea("content", "内容")
                ->keyMultiImage('pic1', "图片")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }


    /**
     * 场地预约报名信息
     */
    public function bmxx($page = 1, $r = 15)
    {
        $admindzz = session("dzzid");

        $state = I('get.state', 100, 'intval');
        $name = I("name","");
        $start = I("start",0,"strtotime");
        $end = I("end",0,"strtotime");

        if(!$name && I("aid") ){
            $name = M("data_hdyg")->getFieldById(I("aid"),"name");
        }

        //读取列表
        $model = M('data_hdbm');
        $map['ljz_data_hdbm.status'] = 1;
        $map['ljz_data_hdyg.type'] = 6;
        if ($state != 100) {
            $map['ljz_data_hdbm.state'] = $state;
        }
        if($name){
            $map['ljz_data_hdyg.name'] = array("like","%".$name."%");
        }
        if($start){
            $map["ljz_data_hdbm.starttime"] =array("gt",$start);
        }
        if($end){
            $map["ljz_data_hdbm.endtime"] =array("lt",$end+3600*24);
        }

        if($admindzz){
            $map['ljz_data_hdyg.dzz'] = $admindzz;
            $totalCount = $model->where($map)->join('left join ljz_data_hdyg on ljz_data_hdyg.id = ljz_data_hdbm.aid')->count();
            $list = $model->where($map)->field('ljz_data_hdbm.*,ljz_data_hdyg.name as aname,ljz_data_hdyg.type as atype')->page($page, $r)->join('left join ljz_data_hdyg on ljz_data_hdyg.id = ljz_data_hdbm.aid')->order('ljz_data_hdbm.starttime desc')->select();
        }else {
            $totalCount = $model->where($map)->join('left join ljz_data_hdyg on ljz_data_hdyg.id = ljz_data_hdbm.aid')->count();
            $list = $model->where($map)->field('ljz_data_hdbm.*,ljz_data_hdyg.name as aname,ljz_data_hdyg.type as atype')->page($page, $r)->join('left join ljz_data_hdyg on ljz_data_hdyg.id = ljz_data_hdbm.aid')->order('ljz_data_hdbm.starttime desc')->select();
        }
        //$atype_map = array("1" => "文化体育活动", "2" => "群团活动", "3" => "公益活动","6"=>"场地预约");
        $statemap = array("0" => "待审核", "1" => "通过审核", "2" => "未通过审核","3"=>"用户取消");
        foreach ($list as &$v) {
           // $v['atype_name'] = $atype_map[$v['atype']];
            $v['state_str'] = $statemap[$v['state']];
            if($v["state"] == 0 ){
                //dump(cdyyConflict($v["id"]));
                if(cdyyConflict($v["id"])){
                    $v["conflict"]  = 1;
                }
            }
            if($name){
                $v["aname"]=str_replace($name,"<span style='color: red' >$name</span>",$v["aname"]);
            }
        }
        unset($v);

        $select['title'] = "审核状态";
        $select['name'] = "state";
        $select['arrvalue'] = array(array("id" => "100", "value" => "全部"),
            array("id" => "0", "value" => "待审核"),
            array("id" => "1", "value" => "审核通过"),
            array("id" => "2", "value" => "审核未通过"));
        $selects[] = $select;
        $this->assign('selects', $selects);
        $this->assign('selectPostUrl', U("bmxx"));

        $pager = new \Think\Page($totalCount, $r, $_REQUEST);
        $pager->setConfig('theme', '%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
        $paginationHtml = $pager->show();
        $this->assign('pagination', $paginationHtml);
        $this->assign("list", $list);
        $this->assign("name", $name);
        $this->assign("searchPostUrl", U('bmxx'));
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $this->display();
    }

    public function cdsh($id){
        if(IS_POST){
//            if($_POST["state"] == 2){
//              $data['reason'] = trim($_POST["reason"]);
//               if(!$data['reason']){
//                   $this->error("请填写未通过原因");
//                   exit;
//               }
//            }
            $data["id"] =$id;
            $data["state"] =$_POST["state"];
            if($data["state"]){
                if($data["state"]  == 1&& cdyyConflict($id)){
                    $this->error("设置失败,与已通过审核的预约有时间冲突，请重新审核");
                    exit;
                }
                $res = M("data_hdbm")->save($data);
                if($res){
//                    $bm = M("data_hdbm")->find($id);
//                    $cd = M("data_hdyg")->find($bm['aid']);
//                    if($data["state"]  == 1){
//                        smsljz($bm["mobile"],"您好，".$bm['name']." ，您预约的场地".$cd['name']."已通过审核，预约时段为".date("Y年m月d日H点i分",$bm['starttime'])."至".date("Y年m月d日H点i分",$bm['endtime'])."，请提前到达。");
//                    }else if($data["state"] == 2){
//                        smsljz($bm["mobile"],"您预约的场地".$cd['name']."未通过审核，工作人员会电话联系您告知原因。谢谢您的理解！");
//                    }
                    $this->success("设置成功", Cookie('__forward__'));
                    exit;
                }else{
                    $this->error("设置失败");exit;
                }
            }else{
                $this->error("参数错误");exit;
            }
        }else{
            $data = M("data_hdbm")->find($id);
            $cd = M("data_hdyg")->find($data['aid']);
            $map["aid"] = $data["aid"];
            $map['state'] =1;
            $map['starttime'] =array("gt",time());
            $yylist = M("data_hdbm")->where($map)->order("starttime asc")->select();
            $this->assign("yylist",$yylist);
            $data["aname"] = $cd["name"];
            $hdsb=M("data_hdsb")->where(array("id"=>array("in",$data["sb"])))->select();
            $this->assign("hdsb",implode(",",array_column($hdsb,"name")));
            $this->assign("data",$data);
            $this->display();
        }
    }

    public function setBmStatus()
    {
        $ids = I('id');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_hdbm', $ids, $status);
    }

    public function setBmState()
    {
        $ids = I('id');
        $state = I('get.state', 0, 'intval');
        $info=  M("data_hdbm")->find($ids);
        $ainfo = M("data_hdyg")->find($info["aid"]);
        $mobile = $info["mobile"];
        if($state == 1){
            smsljz($mobile,"您预约的场地".$ainfo['name']."已通过审核");
        }else if($state == 2){
            smsljz($mobile,"您预约的场地".$ainfo['name']."未通过审核,请知悉");
        }

        $builder = new AdminListBuilder();
        $builder->doSetState('data_hdbm', $ids, $state);
    }

    public function cdyyDetail($id){
        $map['id'] = $id;
        $data = M('data_hdbm')->where($map)->find();
        $info = M('data_hdyg')->find($data["aid"]);

        $data["createtimestr"] = date("Y-m-d H:i:s",$data["create_time"]);
        $data["starttimestr"] = date("Y-m-d H:i:s",$data["starttime"]);
        $data["endtimestr"] = date("Y-m-d H:i:s",$data["endtime"]);
        $data["aname"] = $info["name"];
        if($data['sb']){
            $sbs = M("data_hdsb")->where(array($data['sb']=>array("in",$data["sb"])))->field("name")->select();
            $data["sbstr"] = implode(",",array_column($sbs,"name"));
        }
        $statemap = array("0" => "待审核", "1" => "通过审核", "2" => "未通过审核","3"=>"用户取消");
        $data["statestr"] =$statemap[$data['state']];

        $builder = new AdminConfigBuilder();
        $builder->title("预约详情")
            ->keyLabel('name', "预约人")
            ->keyLabel('aname', "预约场地名称")
            ->keyLabel('mobile', "预约人电话")
            ->keyLabel('createtimestr', "预约创建时间")
            ->keyLabel('starttimestr', "预约使用开始时间")
            ->keyLabel('endtimestr', "预约使用结束时间")
            ->keyLabel('company', "预约部门")
            ->keyLabel('content', "活动内容")
            ->keyLabel('count', "使用人数")
            ->keyLabel('sbstr', "设备要求")
            ->keyLabel('statestr', "审核状态")
            ->data($data)
            ->buttonBack()
            ->display();
    }

    /**
     * 编辑预约信息
     */
    public function edityy(){
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $m = M('data_hdbm');
            $data["create_time"]=time();
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdbm')->where($map)->find();
            }

            unset($map);
            $map["type"] = 6;
            $map["status"] = 1;
            $cds = M("data_hdyg")->where($map)->field("id,name")->order('sort desc')->select();
            $cdopt = array_combine(array_column($cds,"id"),array_column($cds,"name"));

            $data['type'] = 5;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "预约信息")
                ->keyText('name', "预约人姓名")
                ->keyText('mobile', "预约人电话")
                ->keySelect("aid","场地名称","",$cdopt)
                ->keyTextArea("content", "活动内容")
                ->keyText("count", "人数")
                ->keyText("company", "预约部门")
                ->keyTime('starttime', "预约使用开始时间")
                ->keyTime('endtime', "预约使用结束时间")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    public function hd($page = 1, $r = 10){
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('egt',0);
        $map['type'] = 1;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->order("date desc")->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('活动')
            ->buttonNew(U('editHd'))
            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()    ->buttonNew(U('export',array('type'=>1)),'导出excel')
            ->keyId()->keyText('name', '活动主题')
            ->keyText('addr', '地址')
            ->keyText('date', '时间')
            ->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyDoActionEdit('editHd?id=###')
            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("setHdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("setHdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("Hdyg/activity_export?id=###", "word导出")
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    /**
     *活动预约word导出
     */
    public function activity_export()
    {

        $map['status'] = array('egt',0);
        $map['type'] = 1;
        $map['id'] = I('id');
        $model = M('data_hdyg');
        $list = $model->where($map)->find();
        $list['time'] = time();
        $list['date'] = date('Y-m-d',$list['date']);

        $class_img = $model ->where($map)->field('id,imgs')->select();
        foreach ($class_img as $k=>&$v){
            $img_id = explode(',',$v['imgs']);
            foreach ($img_id as $k=>$value){
                $items = get_cover($value);
                $imgs[$k]['path'] =  'http://hqdj.cmlzjz.com'.$items['path'];
            }

        }
        $this->assign('list',$list);
        $this->assign('imgs',$imgs);

        $file = iconv("utf-8", "GBK", '合庆镇社区党建服务中心主题党日活动记录'); //防止导出乱码
        header("Content-Type:   application/msword");
        header("Content-Disposition:   attachment;   filename=$file.doc"); //指定文件名称
        header("Pragma:   no-cache");
        header("Expires:   0");
        $html = $content = $this->fetch('activity_table');//获取模板内容信息word是模板的名称
        echo  $html;


    }



    public function editHd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 1;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 1;
            $builder = new AdminConfigBuilder();//http://hqdj.cmlzjz.com/home/ljz/hdlist
            $builder->title($title . "活动")
                ->keyText('name', "标题")
                ->keySelect('dq','分类','',array(1=>'党建活动',2=>'党群之家活动'))
                ->keyText('zb', "组织单位")
                ->keyMultiImage('imgs', "活动照片")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    /*
 * 党建工作添加*/
    public function djgzAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_djgz');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_djgz')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title($title . "党建工作")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(1=>'党建服务站',2=>'党建+'))
//                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('time', "时间")
//                ->keyText("count", "人数")
                ->keyText("wxlink", "跳转微信链接",'可空')
                ->keyEditor("content", "内容",'','',array('width' => '100%', 'height' => '700px'))
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党建工作管理*/
    public function djgz($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
            $map['type'] = $type;
        }
        $model = M('data_djgz');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 1){
                $v['type_ele'] = "党建服务站";
            }else if($v['type'] == 2){
                $v['type_ele'] = "党建+";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(array("id" => 1, "value" => "党建服务站"),
            array("id" => 2, "value" => "党建+"),
        );
        $builder->title('活动')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('djgzAdd'))
            ->setStatusUrl(U('djgzStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('djgzAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("djgzStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("djgzStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function djgzStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_djgz', $ids, $status);

    }

    /*
     * 党校介绍*/
    public function sqdxAdd($id){
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $m = M('data_djgz');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_sqdx')->where($map)->find();
            }
            $builder = new AdminConfigBuilder();
            $builder->title('党校'.$title)
                ->keyText('title', '党校全称')
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyEditor('content', '介绍')
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
}
