<?php
/**
 * Created by PhpStorm.
 * User: caipeichao
 * Date: 14-3-11
 * Time: PM5:41
 */

namespace Admin\Controller;

use Admin\Builder\AdminConfigBuilder;
use Admin\Builder\AdminListBuilder;
use Admin\Builder\AdminTreeListBuilder;


/**
 * 身边党课
 * @package Admin\Controller
 */
class SbdkController extends AdminController
{
    protected $issueModel;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index($page = 1, $r = 10)
    {
        $this->redirect("dklb");
    }

    /**党课列表
     * @param int $page
     * @param int $r
     */
    public function dklb($page = 1, $r = 10)
    {
        //读取列表
        $map["status"] = 1;
        $model = M('apply_djkc');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();
        //显示页面
        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('党课列表')
            ->buttonNew(U("editdk"))
            ->setStatusUrl(U('setDkStatus'))
            ->buttonDelete()
            ->buttonNew(U('Hdyg/export',array('type'=>'dk')),'导出excel')
            ->keyId()
            ->keyText('jbdw', '举办单位')
            ->keyText('course_name', '党课名称')
            ->keyText('teacher', '授课老师')
            ->keyText('contacter', "联系人")
            ->keyText('contact', "联系电话")
            ->keyText('count', '教室容量')
            ->keyTime("datetime", "授课时间")
            ->keyDoActionEdit('Sbdk/editDk?id=###')
            ->keyDoAction("Sbdk/yylist?aid=###", "查看报名人员")
            ->keyDoAction("Sbdk/word_export?id=###", "word导出")
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    /**
     * 党课列表word导出
     */
    public function word_export()
    {
        $model = M('apply_djkc');
        $map["status"] = 1;
        $map['id'] = I('id');

        //统计报名数
        $Model = M('data_dkbm');
        $where['aid'] = I('id');
        $where['status'] = 1;
        $totalCount = $Model->where($where)->count();

        $list = $model->where($map)->find();
        $list['time'] = time();

        $class_img = $model ->where($map)->field('id,cover_id')->select();
        foreach ($class_img as $k=>&$v){
            $img_id = explode(',',$v['cover_id']);
            foreach ($img_id as $k=>$value){
                $items = get_cover($value);
                $imgs[$k]['path'] =  'http://hqdj.cmlzjz.com'.$items['path'];
            }

        }

        $this->assign('imgs',$imgs);
        $this->assign('list',$list);
        $this->assign('num',$totalCount);

        $file = iconv("utf-8", "GBK", '合庆镇社区党校课程记录'); //防止导出乱码
        header("Content-Type:   application/msword");
        header("Content-Disposition:   attachment;   filename=$file.doc"); //指定文件名称
        header("Pragma:   no-cache");
        header("Expires:   0");
        $html = $content = $this->fetch('class_table');//获取模板内容信息word是模板的名称
        echo  $html;
    }

    public function yylist($page = 1, $r = 10)
    {
        $aid = I('aid', 0, 'intval');

        $kc = M('apply_djkc')->where(array("id" => $aid))->find();
        //读取列表
        $map['aid'] = $aid;
        $map['status'] = 1;
        $model = M('data_dkbm');
        $list = $model->where($map)->page($page, $r)->select();
        $totalCount = $model->where($map)->count();

        //显示页面
        $builder = new AdminListBuilder();
        $builder->title("\"" . $kc['course_name'] . "\"报名人员")
            ->keyText('name', '姓名')->keyText('mobile', '联系电话')->keyCreateTime('create_time', '报名时间')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    public function setDkStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('apply_djkc', $ids, $status);
    }

    /**
     * 党课编辑添加
     */
    public function editDk()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['create_time'] = time();
            $data['mtype'] = 1;
            $Model = M('apply_djkc');

            if ($data["id"]) {
                if ($Model->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($Model->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            $data = array();
            if ($is_edit) {
                $data = M('apply_djkc')->where(array('id' => $id))->find();
            }
            $mapp['mtype'] = 1;
            $mapp['status'] = 1;
            $js = M('data_js')->where($mapp)->field('id,name')->select();
            $jss = array();
            foreach($js as $v){
                $jss[$v['id']] = $v['name'];
            }
            $jss[null] = '空';
//            dump($jss) ;exit;
            $builder = new AdminConfigBuilder;
            $builder->title($title . "党课");
            $builder->keyId()
                ->keyText("jbdw", "举办单位")
//                ->keyText("date", "举办时间")
                ->keyTime("datetime", "举办时间(用于排序)")
                ->keyText("datestr", "举办时间(用于前台展示)")
                ->keySelect('jsID','绑定讲师','可空',$jss)
                ->keyText("course_name", "党课名称")
                ->keyTextArea("content", "党课内容")
                ->keyMultiImage('cover_id', "课程图片")
                ->keyText("teacher", "授课教师")
                ->keyText("tsrc", "教师来源")
                ->keyBDMap("addr|lat|lng","授课地址")
                ->keyText("contacter", "联系人")
                ->keyText("contact", "联系电话")
                ->keyText("count", "教室容量")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }


    /**党课讲师
     * @param int $page
     * @param int $r
     */
    public function js($page = 1, $r = 10)
    {
        //读取列表
        $map["status"] = 1;
        $map["mtype"] = 1;
        $model = M('data_js');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
        }
        //显示页面
        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('讲师风采')
            ->buttonNew(U("editjs"))
            ->setStatusUrl(U('setJsStatus'))->buttonDelete()
            ->keyId()
            ->keyImage('avatar',"图片")
            ->keyText('name', '姓名')
            ->keyText('sex_str', '性别')
            ->keyText('company', '单位名称')
            ->keyText("desc", '简介')
            ->keyDoActionEdit('Sbdk/editJs?id=###')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }


    public function setJsStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_js', $ids, $status);
    }

    /**
     * 讲师编辑添加
     */
    public function editJs()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['create_time'] = time();
            $Model = M('data_js');
            if ($data["id"]) {
                if ($Model->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($Model->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            $data = array();
            if ($is_edit) {
                $data = M('data_js')->where(array('id' => $id))->find();
            }
            $data['mtype'] = 1;//讲师
            $builder = new AdminConfigBuilder;
            $builder->title($title . "讲师");
            $builder->keyId()
                ->keyText("name", "姓名")
                ->keySelect('sex',"性别","",array("1"=>"男","2"=>"女"))
                ->keyText('company', '单位名称')
                ->keySingleImage('avatar',"头像")
                ->keySingleImage('pic',"图片")
                ->keyTextArea("desc", "简介")
                ->keyHidden("mtype","")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }


    /**书记
     * @param int $page
     * @param int $r
     */
    public function sj($page = 1, $r = 10)
    {
        //读取列表
        $map["status"] = 1;
        $map["mtype"] = 2;
        $model = M('data_js');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
        }
        //显示页面
        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('带教书记')
            ->buttonNew(U("editSj"))
            ->setStatusUrl(U('setJsStatus'))->buttonDelete()
            ->keyId()
            ->keyImage('avatar',"图片")
            ->keyText('name', '姓名')
            ->keyText('sex_str', '性别')
            ->keyText('zw', '职务')
            ->keyText('title', '标题')
            ->keyDoActionEdit('Sbdk/edit_record?id=###')
//            ->keyDoActionEdit('Sbdk/shuji_export?id=###')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /**
     * 书记带教记录
     */

    public function sj_record($page = 1, $r = 10)
    {
        //读取列表
        $map["status"] = 1;
        $map["mtype"] = 2;
        $model = M('data_js');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
        }
        //显示页面
        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('带教书记')
            ->buttonNew(U("edit_Sj"))
            ->setStatusUrl(U('setJsStatus'))->buttonDelete()
            ->keyId()
            ->keyImage('avatar',"图片")
            ->keyText('name', '姓名')
            ->keyText('date', '带教时间')
            ->keyText('address', '地点')
            ->keyText('title', '标题')
            ->keyDoActionEdit('Sbdk/edit_Sj?id=###')
            ->keyDoAction("Sbdk/shuji_export?id=###", "word导出")
//            ->keyDoActionEdit('Sbdk/shuji_export?id=###')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }



    public function edit_Sj()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['create_time'] = time();
            $Model = M('data_js');
            if ($data["id"]) {
                if ($Model->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($Model->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            $data = array();
            if ($is_edit) {
                $data = M('data_js')->where(array('id' => $id))->find();
            }
            $data['mtype'] = 2;//书记
            $builder = new AdminConfigBuilder;
            $builder->title($title . "带教书记");
            $builder->keyId()
                ->keyText("name", "姓名")
                ->keySelect('sex',"性别","",array("1"=>"男","2"=>"女"))
                ->keyText('zw', '职务')
                ->keySingleImage('avatar',"头像")
                ->keySingleImage('pic',"图片")
                ->keyMultiImage('imgs', "活动照片")
                ->keyText("title", "标题")
                ->keyText('date','带教时间')
                ->keyText('region','带教片区')
                ->keyText('address','地点')
                ->keyRichText("desc", "简介")
                ->keyHidden("mtype","")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }


    /**
     * 书记带教导出
     */

    public function shuji_export()
    {

        $map["status"] = 1;
        $map["mtype"] = 2;
        $map['id'] = I('id');
        $model = M('data_js');
        $list = $model->where($map)->find();
        $list['time'] = time();
        $class_img = $model ->where($map)->field('id,imgs')->select();
        foreach ($class_img as $k=>&$v){
            $img_id = explode(',',$v['imgs']);
            foreach ($img_id as $k=>$value){
                $items = get_cover($value);
                $imgs[$k]['path'] =  'http://hqdj.cmlzjz.com'.$items['path'];
            }

        }

        $this->assign('list',$list);
        $this->assign('imgs',$imgs);

        $file = iconv("utf-8", "GBK", '合庆书记工作室带教记录'); //防止导出乱码
        header("Content-Type:   application/msword");
        header("Content-Disposition:   attachment;   filename=$file.doc"); //指定文件名称
        header("Pragma:   no-cache");
        header("Expires:   0");
        $html = $content = $this->fetch('shuji_table');//获取模板内容信息word是模板的名称
        echo  $html;


    }

    /**
     * 书记编辑添加
     */
    public function edit_record()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['create_time'] = time();
            $Model = M('data_js');
            if ($data["id"]) {
                if ($Model->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($Model->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            $data = array();
            if ($is_edit) {
                $data = M('data_js')->where(array('id' => $id))->find();
            }
            $data['mtype'] = 2;//书记
            $builder = new AdminConfigBuilder;
            $builder->title($title . "带教书记");
            $builder->keyId()
                ->keyText("name", "姓名")
                ->keySelect('sex',"性别","",array("1"=>"男","2"=>"女"))
                ->keyText('zw', '职务')
                ->keySingleImage('avatar',"头像")
                ->keySingleImage('pic',"图片")
                ->keyMultiImage('imgs', "活动照片")
                ->keyText("title", "标题")
                ->keyRichText("desc", "简介")
                ->keyHidden("mtype","")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }

    /*
     * 书记预约*/
    public function sjyy($page = 1, $r = 10){
        //读取列表
        $map["status"] = 1;
        $model = M('data_sjyy');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
        }
        //显示页面
        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('带教书记')
            ->buttonNew(U("editSj"))
            ->setStatusUrl(U('setJsStatus'))->buttonDelete()
            ->keyId()
            ->keyImage('avatar',"图片")
            ->keyText('name', '姓名')
            ->keyText('sex_str', '性别')
            ->keyText('zw', '职务')
            ->keyText('title', '标题')
            ->keyDoActionEdit('Sbdk/editSj?id=###')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /**
     * 报名信息
     */
    public function bmxx($page = 1, $r = 10)
    {
        $state = I('get.state', 100, 'intval');
//        $_GET['state'] = $state;
        //读取列表
        $map['ljz_data_dkbm.status'] = 1;
        if ($state != 100) {
            $map['ljz_data_dkbm.state'] = $state;
        }
        $model = M('data_dkbm');
        $list = $model->where($map)->field('ljz_data_dkbm.*,ljz_apply_djkc.course_name as aname')->page($page, $r)->join('left join ljz_apply_djkc on ljz_data_dkbm.aid = ljz_apply_djkc.id')->order('ljz_data_dkbm.create_time desc')->select();
        $statemap = array("0" => "待审核", "1" => "报名成功", "2" => "已取消");
        foreach ($list as &$v) {
            $v['state_str'] = $statemap[$v['state']];
        }

        $select['title'] = "审核状态";
        $select['name'] = "state";
        $select['arrvalue'] = array(array("id" => "100", "value" => "全部"),
            array("id" => "0", "value" => "待审核"),
            array("id" => "1", "value" => "报名成功"),
            array("id" => "2", "value" => "已取消"));
        $selects[] = $select;
        $this->assign('selects', $selects);
        $this->assign('selectPostUrl', U("bmxx"));

        $totalCount = $model->where($map)->count();
        $pager = new \Think\Page($totalCount, $r, $_REQUEST);
        $pager->setConfig('theme', '%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
        $paginationHtml = $pager->show();
        $this->assign('pagination', $paginationHtml);
        $this->assign("list", $list);
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $this->display();
//        //显示页面
//        $builder = new AdminListBuilder();
//        $builder->title("报名信息")
//            ->setStatusUrl(U('setBmStatus'))->buttonDelete()
//            ->keyText('name', '姓名')
//            ->keyText('mobile', '联系电话')
//            ->keyCreateTime('create_time', '报名时间')
//            ->keyText("aname", "活动名称")
//            ->keyText('num', '报名人数')
//            ->keyText("state","报名状态")
//            ->data($list)
//            ->pagination($totalCount, $r)
//            ->display();
    }

//    /**
//     * 报名信息编辑
//     */
//    public function editBmxx(){
//        $id = I('id', 0, 'intval');
//        $is_edit = $id ? 1 : 0;
//        $title = $is_edit ? "编辑" : "添加";
//        if (IS_POST) {
//            $data = $_POST;
//            $data['create_time'] = time();
//            $Model = M('apply_djkc');
//            if ($data["id"]) {
//                if ($Model->save($data) !== false) {
//                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
//                } else {
//                    $this->error(L('_FAIL_UPDATE_'));
//                }
//            } else {
//                if ($Model->add($data) !== false) {
//                    $this->success("添加成功", Cookie('__forward__'));
//                } else {
//                    $this->error("添加失败");
//                }
//            }
//        } else {
//            $data = array();
//            if ($is_edit) {
//                $data = M('apply_djkc')->where(array('id' => $id))->find();
//            }
//            $builder = new AdminConfigBuilder;
//            $builder->title($title . "报名");
//            $builder->keyId()
//                ->keyText("name", "报名人姓名")
//                ->keyTime("mobile","联系方式")
//                ->keyText("num", "报名人数")
//                ->keyText("teacher", "授课教师")
//                ->keyText("tsrc", "教师来源")
//                ->keyText("addr", "授课地址")
//                ->keyText("contacter", "联系人")
//                ->keyText("contact", "联系电话")
//                ->keyText("count", "教室容量")
//                ->buttonSubmit()
//                ->buttonBack()
//                ->data($data)
//                ->display();
//        }
//    }


    public function setBmStatus()
    {
        $ids = I('id');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dkbm', $ids, $status);
    }

    public function setBmState()
    {
        $ids = I('id');
        $state = I('get.state', 0, 'intval');
		if($state==1){
			$data = M("data_dkbm")->where('id='.$ids)->find();
			$kcdata = M("apply_djkc")->where('id='.$data['id'])->find();
			smsljz($data['mobile'], $msg = '您好:' . $data['name'] . ',您预约的党课《'.$kcdata['course_name'].'》已被管理员审核批准，请及时上课并做签到！！ 联系电话：68871363');
		}
        $builder = new AdminListBuilder();
        $builder->doSetState('data_dkbm', $ids, $state);



    }

    /*
     * 党校活动照片*/
    public function dxzpAdd($id=null){
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_dxzp');
            $data['time'] = time();
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_dxzp')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title('活动照片展示' . $title)
                ->keyText('title', '照片备注')
                ->keySingleImage('img','图片上传')
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党校照片管理*/
    public function dxzp($page = 1, $r = 15){

        //读取列表
        $map['status'] = array('egt',0);
        $model = M('data_dxzp');
        $list = $model->where($map)->page($page, $r)->select();
        $totalCount = $model->where($map)->count();
        $builder = new AdminListBuilder();
        $builder->title('活动照片')
//            ->buttonNew(U('editHd'))
//            ->setStatusUrl(U('setHdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
//            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
//            ->keyText('zb', '组织单位')
            ->buttonNew(U('dxzpAdd'))
            ->keyId()
            ->keyStatus('status', '状态')
            ->keyImage('img', '活动照片', array("width" => 24, "height" => 24 ,"style"=>"border-radius:0;"))
            ->keyDoActionEdit('dxzpAdd?id=###')
            ->keyDoAction("dxzpStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("dxzpStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function dxzpStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        if($status == 1){
            $count = M('data_dxzp')->where(array('status'=>1))->count()  ;
            if($count >5 ){
                $this-> error('最多显示5张') ;
            }
        }
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dxzp', $ids, $status);

    }
}
