<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2017/12/1
 * Time: 17:30
 */

namespace Admin\Controller;


use Admin\Builder\AdminConfigBuilder;
use Admin\Builder\AdminListBuilder;

class WxdjController  extends AdminController
{
    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
    /*
    * 党建风采*/
    public function djfcAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_djfc');
           if(!$data['type']){
              $this->error(L('分类未选择'));
           }
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_djfc')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title($title . "党建风采")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(1=>'美丽合庆一路有你风采录',2=>'我身边的优秀党员'))
//                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('time', "时间")
//                ->keyText("count", "人数")
//                ->keyText("count", "人数")
                ->keyText("wxlink", "跳转微信链接",'可空')

                ->keyEditor("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党建风采管理*/
    public function djfc($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
                    $map['type'] = $type;
        }

        $model = M('data_djfc');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 1){
                $v['type_ele'] = "美丽合庆一路有你风采录";
            }else if($v['type'] == 2){
                $v['type_ele'] = "我身边的优秀党员";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(
            array("id" => null, "value" => "未选择"),

            array("id" => 1, "value" => "美丽合庆一路有你风采录"),
            array("id" => 2, "value" => "我身边的优秀党员"),
        );
        $builder->title('党建风采')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('djfcAdd'))
            ->setStatusUrl(U('djfcStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('djfcAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("djfcStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("djfcStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /*
     * 党建风采管理*/
    public function djfcStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_djfc', $ids, $status);

    }
    /**
     * 编辑预约信息
     */
    public function edityy(){
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $m = M('data_hdbm');
            $data["create_time"]=time();
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdbm')->where($map)->find();
            }

            unset($map);
            $map["type"] = 6;
            $map["status"] = 1;
            $cds = M("data_hdyg")->where($map)->field("id,name")->order('sort desc')->select();
            $cdopt = array_combine(array_column($cds,"id"),array_column($cds,"name"));

            $data['type'] = 5;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "预约信息")
                ->keyText('name', "预约人姓名")
                ->keyText('mobile', "预约人电话")
                ->keySelect("aid","场地名称","",$cdopt)
                ->keyTextArea("content", "活动内容")
                ->keyText("count", "人数")
                ->keyText("company", "预约部门")
                ->keyTime('starttime', "预约使用开始时间")
                ->keyTime('endtime', "预约使用结束时间")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    /*
     * 合心圆*/
    public function hxy($page = 1, $r = 10){
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzz"]  = $admindzz;
        }
        //读取列表
        $map['status'] = array('egt',0);
        $map['type'] = 10;
        $model = M('data_hdyg');
        $list = $model->where($map)->page($page, $r)->order("date desc")->select();

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('合心圆')
            ->buttonNew(U('editHd'))
            ->setStatusUrl(U('hxyStatuss'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('name', '活动主题')->keyText('addr', '地址')->keyText('date', '时间')->keyText('count', '人数')
            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyDoActionEdit('editHd?id=###')
            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("hxyStatuss?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("hxyStatuss?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))

            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function hxyStatuss()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_hdyg', $ids, $status);

    }


    public function editHd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 10;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 1;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "活动")
                ->keyText('name', "标题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }

    public function editHxy()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";

        if (IS_POST) {
            $data = $_POST;
            $data['type'] = 10;
            $admindzz = session("dzzid");
            $user = session('user_auth');
            $data["editor"] = $user['uid'];
            if($admindzz) {
                $data["dzz"] = $admindzz;
            }

            $m = M('data_hdyg');
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_hdyg')->where($map)->find();
            }
            $data['type'] = 1;
            $builder = new AdminConfigBuilder();
            $builder->title($title . "活动")
                ->keyText('name', "标题")
                ->keyText('zb', "组织单位")
                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('date', "时间")
                ->keyText("count", "人数")
                ->keyTextArea("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 报名管理*/
    public function bmlist2($page = 1, $r = 10)
    {
        $aid = I('aid', 0, 'intval');

        $kc = M('data_hdyg')->where(array("id" => $aid))->find();
        //读取列表
        $map['aid'] = $aid;
        $map['status'] = 1;
        $map['state'] = array("in" ,array(0,1,2));
        $model = M('data_hdbm');
        $list = $model->where($map)->page($page, $r)->order("starttime desc")->select();
        $totalCount = $model->where($map)->count();

        if($kc["type"] == 6){
            //$builder->keyText()
            foreach ($list as &$v){
                $v["yytime"]=date("Y-m-d H:i:s",$v["starttime"])."—".date("Y-m-d H:i:s",$v["endtime"]);
            }
        }
        unset($v);

        //显示页面
        $builder = new AdminListBuilder();
        $builder->title("\"" . $kc['name'] . "\"报名人员")
            ->keyText('name', '姓名')->keyText('mobile', '联系电话')->keyCreateTime('create_time', '创建时间');

        if($kc["type"] == 6){
            $builder->keyText("yytime","预约时间段");
            $builder->keyText("company","预约部门");
        }
        $builder->data($list)
            ->pagination($totalCount, $r)
            ->keyStatus('state')
            ->buttonDisable(U('hxyStatus',array('state'=>1)),L('通过'))
            ->buttonDisable(U('hxyStatus',array('state'=>0)),L('禁止'))
            ->buttonDisable(U('hxyStatus',array('state'=>-1)),L('删除'))
            ->display();
    }
    /*
    * 合心圆报名人员管理*/
    public function hxyStatus(){
        $ids = I('ids');
        $state = I('get.state', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetState('data_hdbm', $ids, $state);
    }

    /*
     * 党群之家*/
    public function dqzjAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_dqzj');
            if(!$id){
                if(!$data['type']){
                    $this->error(L('分类未选择'));
                }
            }

            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_dqzj')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title($title . "党建风采")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(0=>'请选择',3=>'政策解答',4=>'活动展示'))//1=>'团委征文',2=>'工青妇活动展示',
//                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('time', "时间")
//                ->keyText("count", "人数")
                ->keyText("wxlink", "跳转微信链接",'可空')

                ->keyEditor("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党群之家管理*/
    public function dqzj($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
            $map['type'] = $type;
        } else{
            $map['type'] = array('elt',4);

        }

        $model = M('data_dqzj');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 1){
                $v['type_ele'] = "团委征文";
            }else if($v['type'] == 2){
                $v['type_ele'] = "工青妇活动展示";
            } else if($v['type'] == 3){
                $v['type_ele'] = "政策解答";
            }else if($v['type'] == 4){
                $v['type_ele'] = "活动展示";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(
            array("id" => null, "value" => "未选择"),
//
//            array("id" => 1, "value" => "团委征文"),
//            array("id" => 2, "value" => "工青妇活动展示"),
            array("id" => 3, "value" => "政策解答"),
            array("id" => 4, "value" => "活动展示")
        );
        $builder->title('党群之家')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('dqzjAdd'))
            ->setStatusUrl(U('dqzjStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('dqzjAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("dqzjStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("dqzjStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /*
     * 党群之家管理*/
    public function dqzjStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dqzj', $ids, $status);

    }

    /*
   * 党建百科*/
    public function djbkAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_dqzj');
            if(!$id){
                if(!$data['type']){
                    $this->error(L('分类未选择'));
                }
            }

            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_dqzj')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title($title . "党建风采")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(5=>'党务实务',6=>'党建知识',7=>'两学一做',8=>'党史回顾'))
//                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('time', "时间")
//                ->keyText("count", "人数")
                ->keyText("wxlink", "跳转微信链接",'可空')
                ->keyEditor("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党建百科管理*/
    public function djbk($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
            $map['type'] = $type;
        }else{
            $map['type'] = array('egt',5);
        }

        $model = M('data_dqzj');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 5){
                $v['type_ele'] = "党务实务";
            }else if($v['type'] == 6){
                $v['type_ele'] = "党建知识";
            } else if($v['type'] == 7){
                $v['type_ele'] = "两学一做";
            }else if($v['type'] == 8){
                $v['type_ele'] = "党史回顾";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(
            array("id" => null, "value" => "未选择"),
            array("id" => 5, "value" => "党务实务"),
            array("id" => 6, "value" => "党建知识"),
            array("id" => 7, "value" => "两学一做"),
            array("id" => 8, "value" => "党史回顾")
        );
        $builder->title('党建百科')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('djbkAdd'))
            ->setStatusUrl(U('djbkStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('djbkAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("djbkStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("djbkStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /*
     * 党建百科管理*/
    public function djbkStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dqzj', $ids, $status);

    }





    /*
   * 党课在线 */
    public function dkzxAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_dkzx');
            if(!$id){
                if(!$data['type']){
                    $this->error(L('分类未选择'));
                }
            }

            $data['time']  = time();
            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {

            if ($id) {
                $map['id'] = $id;
                $data = M('data_dkzx')->where($map)->find();
            }

            $builder = new AdminConfigBuilder();
            $builder->title($title . "党课在线")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(2=>'党课回顾',1=>'故事党课'))
                ->keyText("wxlink", "跳转微信链接",'可空')
                ->keyEditor("content", "内容",'','\'fullscreen\', \'source\', \'|\', \'undo\', \'redo\', \'|\',
            \'bold\', \'italic\', \'underline\', \'fontborder\', \'strikethrough\', \'superscript\', \'subscript\', \'removeformat\', \'formatmatch\', \'autotypeset\', \'blockquote\', \'pasteplain\', \'|\', \'forecolor\', \'backcolor\', \'insertorderedlist\', \'insertunorderedlist\', \'selectall\', \'cleardoc\', \'|\',
            \'rowspacingtop\', \'rowspacingbottom\', \'lineheight\', \'|\',
            \'customstyle\', \'paragraph\', \'fontfamily\', \'fontsize\', \'|\',
            \'directionalityltr\', \'directionalityrtl\', \'indent\', \'|\',
            \'justifyleft\', \'justifycenter\', \'justifyright\', \'justifyjustify\', \'|\', \'touppercase\', \'tolowercase\', \'|\',
            \'link\', \'unlink\', \'anchor\', \'|\', \'imagenone\', \'imageleft\', \'imageright\', \'imagecenter\', \'|\',
            \'simpleupload\', \'insertimage\', \'emotion\', \'scrawl\', \'insertvideo\', \'music\', \'attachment\', \'map\', \'gmap\', \'insertframe\', \'insertcode\', \'webapp\', \'pagebreak\', \'template\', \'background\', \'|\',
            \'horizontal\', \'date\', \'time\', \'spechars\', \'snapscreen\', \'wordimage\', \'|\',
            \'inserttable\', \'deletetable\', \'insertparagraphbeforetable\', \'insertrow\', \'deleterow\', \'insertcol\', \'deletecol\', \'mergecells\', \'mergeright\', \'mergedown\', \'splittocells\', \'splittorows\', \'splittocols\', \'charts\', \'|\',
            \'print\', \'preview\', \'searchreplace\', \'help\', \'drafts\'')
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党建百科管理*/
    public function dkzx($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
            $map['type'] = $type;
        }else{
            $map['type'] = array('egt',1);
        }

        $model = M('data_dkzx');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 1){
                $v['type_ele'] = "故事党课";
            }else if($v['type'] == 2){
                $v['type_ele'] = "党课回顾";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(
            array("id" => null, "value" => "未选择"),
            array("id" => 1, "value" => "故事党课"),
            array("id" => 2, "value" => "党课回顾"),

        );
        $builder->title('党课在线')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('dkzxAdd'))
            ->setStatusUrl(U('dkzxStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('dkzxAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("dkzxStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("dkzxStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }
    /*
     * 党建百科管理*/
    public function dkzxStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dkzx', $ids, $status);

    }


    /*
     * 故事征集*/
    public function gszj(){
        $M=M('data_story');
        $map['status'] = array('egt',1);
        $data = $M->where($map)->select();
        $emil = M('back')->order('id desc')->find();
        $b = new AdminListBuilder();
        $b ->title('故事征集')
            ->suggest('当前邮箱：'.$emil['a'])
            ->buttonNew('/admin/wxdj/gszjemil','修改邮箱')
            ->keyText('title','标题')
            ->keyText('name','姓名')
            ->keyText('telephone','电话')
            ->keyTime('time','上传时间')
            ->keyLink('查看','查看',"gszjlook?id=###")
            ->keyDoAction("gszjStatus?ids=###&status=-1", "删除", "操作", array('class' => 'ajax-get'))

            ->data($data)
            ->display();

    }
    public function gszjStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_story', $ids, $status);

    }

    public function gszjlook($id){
        $M=M('data_story');
        $map['id'] = $id  ;
        $data = $M->where($map)->find();
       $imgs = explode(',',$data['img']) ;
        foreach($imgs as $k=>$v){
            $data['imgs'][] = pic($v) ;
        }
        $this->assign('data',$data);
//        dump($data);
        $this->display();
    }

    public function gszjemil(){
        if(IS_POST){
            $data['a'] =  $_REQUEST['assa']  ;
            $id = M('back')->add($data);
            if($id){
                $this->success('修改成功','gszj') ;
            } else{
                $this->error('修改失败');
            }
        }else{
            $b  = new AdminConfigBuilder();
            $b->title('邮箱修改')
                ->keyText('assa','邮箱')
                ->buttonSubmit($this)
                ->buttonBack()
                ->display();
        }
    }



    /*
* 党建活动*/
    public function djhdAdd()
    {
        $id = I('id');
        $title = $id ? "编辑" : "新增";
        if (IS_POST) {
            $data = $_POST;
            $m = M('data_dqzj');
            if(!$id){
                if(!$data['type']){
                    $this->error(L('分类未选择'));
                }
            }

            if ($data["id"]) {
                if ($m->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($m->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            if ($id) {
                $map['id'] = $id;
                $data = M('data_dqzj')->where($map)->find();
            }
            $builder = new AdminConfigBuilder();
            $builder->title($title . "活动")
                ->keyText('title', "标题")
                ->keySelect('type','分类','',array(9=>'党建活动',10=>'区域化党建活动'))
//                ->keyBDMap("addr|lat|lng", "地址")
                ->keyTime('time', "时间")
//                ->keyText("count", "人数")
                ->keyText("wxlink", "跳转微信链接",'可空')
                ->keyEditor("content", "内容")
                ->keyHidden("id","")
                ->data($data)
                ->buttonSubmit()
                ->buttonBack()
                ->display();
        }
    }
    /*
     * 党建活动*管理*/
    public function djhd($page = 1, $r = 28,$type=null){
        //读取列表
        $map['status'] = array('egt',0);
        if($type){
            $map['type'] = $type;
        }else{
            $map['type'] = array('in','9,10');
        }

        $model = M('data_dqzj');
        $list = $model->where($map)->page($page, $r)->order("id desc")->select();
        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['date'] = date('Y-m-d', $v['date']);
            if ($v['status'] == 1) {
                $v['_hide'] = array("启用");
                $v['status_str'] = "正常";
            } else if ($v['status'] == 0) {
                $v['_hide'] = array("禁用");
                $v['status_str'] = "禁用";
            }
            if($v['type'] == 9){
                $v['type_ele'] = "党建活动";
            }else if($v['type'] == 10){
                $v['type_ele'] = "区域化党建活动";
            }
        }

        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $typeopt = array(
            array("id" => null, "value" => "未选择"),
            array("id" => 9, "value" => "党建活动"),
            array("id" => 10, "value" => "区域化党建活动"),
        );
        $builder->title('活动推送')
            ->select('分类查询','type','select','','','',$typeopt)
            ->buttonNew(U('djhdAdd'))
            ->setStatusUrl(U('djhdStatus'))->buttonEnable()->buttonDisable()->buttonDelete()
            ->keyId()->keyText('title', '主题')->keyTime('time', '时间')
//            ->keyText('zb', '组织单位')
            ->keyText('status_str', '状态')
            ->keyText('type_ele', '分类')
            ->keyDoActionEdit('djhdAdd?id=###')
//            ->keyDoAction("bmlist2?aid=###", "查看报名人员")
            ->keyDoAction("djhdStatus?ids=###&status=0", "禁用", "操作", array('class' => 'ajax-get'))
            ->keyDoAction("djhdStatus?ids=###&status=1", "启用", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /*
     * 党建活动*管理*/
    public function djhdStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_dqzj', $ids, $status);

    }

}