<?php
/**
 * Created by PhpStorm.
 * User: caipeichao
 * Date: 14-3-11
 * Time: PM5:41
 */

namespace Admin\Controller;

use Admin\Builder\AdminConfigBuilder;
use Admin\Builder\AdminListBuilder;
use Admin\Builder\AdminTreeListBuilder;
use User\Model\UcenterMemberModel;


class ZzglController extends AdminController
{
    protected $issueModel;

    function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }


    public function maptest()
    {
        //$this->display();

        $builder = new AdminConfigBuilder();
        $builder->title("测试")->keyText('title', "Title")->keyBDMap("address|lng|lat", "地址", "")
            ->keyStatus()->keyCreateTime()->keyUpdateTime()->data(array("address" => "上海市XXXXX", "lat" => "31.243001", "lng" => "121.532246"))
            ->buttonBack()->display();
    }


    public function index($page = 1, $r = 10)
    {
//        if (session("dzzid")) {
//            $this->redirect("dzzcy");
//        }
        $this->redirect("zqdw");
    }


    public function setTransorgStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('trans_org_relation', $ids, $status);

    }

    /**党组织成员
     * @param int $page
     * @param int $r
     */
    public function dzzcy($page = 1, $r = 10,$daochu=0)
    {
        $dzz = I("get.dzz", 0, "intval");
        if ($dzz) {
            $map['ljz_party_member.dzz'] = $dzz;
        }
        $admindzz = session("dzzid");
        if ($admindzz) {
            $map["ljz_party_member.dzz"] = $admindzz;
        }

        $name = I("get.name","");
        if($name){
            $map["ljz_party_member.name"] = array("like","%".$name."%");
        }

        $sex =  I("get.sex", 0, "intval");
        if($sex){
            $map['ljz_party_member.sex'] = $sex;
        }

        $sbd =  I("get.sbd", 0, "intval");
        if($sbd == 1){
            $map['ljz_party_member.sbd'] = 1;
        }elseif($sbd == 2){
            $map['ljz_party_member.sbd'] = array(array("eq",0),array("exp","is null"),"or");
        }
        $zt =  I("get.zt");
        if($zt){
            $map['ljz_party_member.zt'] = $zt;
        }

        $agestart = I("get.agestart", 0, "intval");
        $ageend = I("get.ageend", 0, "intval");
        if($agestart && $ageend){
            $map['ljz_party_member.birthday'] = array(array("gt",strtotime("-$ageend year")),array("lt",strtotime("-$agestart year")),"and");
        }elseif ($agestart){
            $map['ljz_party_member.birthday'] = array("lt",strtotime("-$agestart year"));
        }elseif ($ageend){
            $map['ljz_party_member.birthday'] = array("gt",strtotime("-$ageend year"));
        }



        //读取列表
        $map["ljz_party_member.status"] = 1;
        $model = M('party_member');
        $list = $model->field('ljz_party_member.*,ljz_dzz.name as dzzname')->where($map)->page($page, $r)->join("left join ljz_dzz on ljz_party_member.dzz = ljz_dzz.id ")->select();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex'] = $sexmap[$v['sex']];
            $v["sbd_str"] = $v["sbd"] == 1?"是":"否";
        }
        //excel导出
        if($daochu){
            $xlsCell = array(
                array('xid','序号'),
                array('name','姓名'),
                array('dzzmc','所在党支部'),
                array('idnum','公民身份证号'),
                array('sex','性别'),
                array('mz','民族'),
                array('birth','出生日期'),
                array('whcd','学历'),
                array('dylx','人员类别'),
                array('rddate','加入党组织日期'),
                array('zsdydate','转为正式党员日期'),
                array('gzdw','工作岗位'),
                array('phone','手机号'),
                array('tel','固定电话'),
                array('addr','家庭住址'),
                array('djzt','党籍状态'),
                array('sldy','是否为失联党员'),
                array('slrq','失去联系日期'),
                array('lddy','是否为流动党员'),
                array('wclx','外出流向'),
                array('bz','备注')
            );

            $list2Excel = $model->field('ljz_party_member.*,ljz_dzz.name as dzzname')->where($map)
                ->join("left join ljz_dzz on ljz_party_member.dzz = ljz_dzz.id ")->select();
            foreach ($list2Excel as  $k=>$v){
                if($v['sex']=1){
                    $list2Excel[$k]['sex']='男';
                }else{
                    $list2Excel[$k]['sex']='女';
                }
                $list2Excel[$k]['idnum'] = ' '.$v['idnum'];
                $list2Excel[$k]['xid'] = $k+1;
            }
            $res = exportExcel($xlsName='党员基本信息汇总表',$xlsCell,$list2Excel);
        }

        $totalCount = $model->where($map)->count();
        //显示页面
        $builder = new AdminListBuilder();
//        $attr['class'] = 'btn ajax-post';
//        $attr['target-form'] = 'ids';


        $dzz = M('dzz')->where(array('status' => 1))->order('type,id')->select();
        $dzzoptions = array(
            array('id' => 0, 'value' => "全部", "lvl" => 2),
        );

        $curtype = array();
        foreach ($dzz as $v1) {
            if ($v1['type'] != $curtype['type']) {
                $curtype = $v1;
                $dzzoptions[] = array('id' => "", 'value' => $v1['type'], "lvl" => 1);
            }
            $dzzoptions[] = array('id' => $v1['id'], 'value' => $v1['name'], "lvl" => 2);
        }
        $sexopt = array(array("id"=>0,"value"=>"全部"),array("id"=>1,"value"=>"男"),array("id"=>2,"value"=>"女"));
        $sbdopt = array(array("id"=>0,"value"=>"全部"),array("id"=>1,"value"=>"是"),array("id"=>2,"value"=>"否"));
        $ztopt = array(array("id"=>"","value"=>"全部"),array("id"=>"退休","value"=>"退休"),array("id"=>"在职","value"=>"在职"),array("id"=>"无业","value"=>"无业"));

        $builder->setSelectPostUrl(U("dzzcy"));
        Cookie('__forward__', $_SERVER['REQUEST_URI']);

        $builder->title('党员名单')
            ->buttonNew(U("editDzzcy"))
            ->setStatusUrl(U('setDzzcyStatus'))->buttonDelete();
        $builder->button('导入', array('class' => 'btn btn-info','href' => U('Zzgl/daoru')));
        $builder->button('导出', array('class' => 'btn btn-info','href' => 'http://'.$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']."&daochu=1"));

        if (!$admindzz) {
            $builder->select("党组织：", "dzz", "select", '', '', '', $dzzoptions);
        }

//            ->select("居委：", "jw", "select", '', '', '', $jwoptions)
        $builder->keyId()->keyText('name', '姓名')
//            ->keyText('idnum', '身份证号')
            ->setSearchPostUrl(U("dzzcy"))
            ->search("姓名","name","text")
            ->search("年龄(大于)","agestart","text")
            ->search("年龄(小于)","ageend","text")
            ->select("性别：", "sex", "select", '', '', '', $sexopt)
//            ->select("双报到：", "sbd", "select", '', '', '', $sbdopt)
            ->select("状态：", "zt", "select", '', '', '', $ztopt)
            ->keyText('sex', '性别')
            ->keyText('idnum', '身份证号')
            ->keyText('tel', '电话')
            ->keyText('dzzname', "党组织")
            ->keyText('zt', "状态")
//            ->keyText('sbd_str', "双报到")
            ->keyDoActionEdit('editDzzcy?id=###')
            ->keyDoAction("zzgl/pf?id=###","评分")
            ->data($list)
            ->pagination($totalCount, $r);


        $builder  ->display();
    }

    public function pf($id){
        $map2["status"] = 1;
        $map2["jftype"] = array("in","1,2,3");
        $pftypes =  M("data_jfsd")->where($map2)->order("jftype")->select();
        $pftypeids = array_column($pftypes,"id");


        if(IS_POST){
            $uname = M("party_member")->getFieldById($_POST["id"],"name");
            $data["uid"] =$_POST["id"];
            $data["uname"] = $uname;
            $data["create_time"]=time();
            M("data_pfrecord")->where(array("uid"=>$_POST["id"],"jftype"=>array("in",$pftypeids)))->delete();

            foreach ($pftypes as $item){
                //if($_POST["type_".$item["id"]]){//评分是0的不记录
                    $data["jftype"] = $item["id"];
                    $data["fen"] = $_POST["type_".$item["id"]];
                    M("data_pfrecord")->add($data);
                //}
            }
            unset($item);
//            foreach ($_POST["rid"] as $item) {
//                $data["jftype"]=intval($item);
//                $data["fen"] = M("data_jfsd")->getFieldById($data["jftype"],"fen");
//                M("data_pfrecord")->add($data);
//            }
            $this->success("评分成功",Cookie('__forward__'));
        }else{
            $info =M("party_member")->find($id);

            $map["uid"]=$id;
            $map["status"] = 1;
            $map["jftype"] = array("in",$pftypeids);
            $records = M("data_pfrecord")->where($map)->select();
            $pf = array_combine(array_column($records,"jftype"),array_column($records,"fen"));

            $pftypeopt = array("1"=>"基本分","2"=>"履职分","3"=>"奉献分","4"=>"加减分");

            $curPftype = $pftypes[0]["jytype"];
            $i = 0;
            foreach ($pftypes as &$v){
                $v["fen_get"] = $pf[$v["id"]];
                if($v["jftype"] !=$curPftype){
                    $i = 0;
                    $curPftype =$v["jftype"];
                }
                if($i == 0){
                    $v["jftype_name"]=$pftypeopt[$v["jftype"]];
                    $v["rowspan"] = M("data_jfsd")->where(array("status"=>1,"jftype"=>$v["jftype"]))->count();
                }
                $i++;

                /**
                 * 特定项显示额外信息，
                 */
                //19组织生活-按时参加党课,显示参加党课签到次数
                if(19 == $v["id"]){
                    $openid = M("wxmember")->getFieldByPmid($id,"openid");
                    if($openid){
                        $bmCount = M("data_dkbm")->where(array("openid"=>$openid,"status"=>1,"state"=>1))->count();
                        $count = M("data_dkbm")->where(array("openid"=>$openid,"status"=>1,"state"=>1,"signtime"=>array("gt",0)))->count();
                        $v["extra_info"]="(党课签到$count 次/报名$bmCount 次)";
                    }else{
                        $v["extra_info"]="(还未绑定微信)";
                    }
                }

//                //双向认领
//                if(25 == $v["id"]){
//
//                }

                //公益活动
                if(26  == $v["id"]){
                    $openid = M("wxmember")->getFieldByPmid($id,"openid");
                    if($openid){
                        $bmCount = M("data_hdbm")->where(array("openid"=>$openid,"status"=>1,"state"=>1))->count();
                        $count = M("data_hdbm")->where(array("openid"=>$openid,"status"=>1,"state"=>1,"signtime"=>array("gt",0)))->count();
                        $v["extra_info"]="(活动签到$count 次/报名$bmCount 次)";
                    }else{
                        $v["extra_info"]="(还未绑定微信)";
                    }
                }

            }

            $this->assign("pflist",$pftypes);
            $this->assign("data",$info);
            $this->display();
        }
    }

    public function setDzzcyStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('party_member', $ids, $status);
    }

    public function editDzzcy()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['mgzzsh'] = intval($data['mgzzsh']);
            $data['sbd'] = intval($data['sbd']);
            $data['cgbldj'] = intval($data['cgbldj']);
            $data['dymc'] = intval($data['dymc']);

            $Model = M('party_member');
            if ($data["id"]) {
                if ($Model->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($Model->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            $data = array();
            if ($is_edit) {
                $data = M('party_member')->where(array('id' => $id))->find();
            }

            //所属党组织
            $dzzopt = M("dzz")->where(array("status" => 1))->order("type")->field("name,id")->select();
            array_unshift($dzzopt, array("id" => "", "name" => "-----请选择-----"));

            $mzopt = array("汉族", "壮族", "满族", "回族", "苗族", "维吾尔族", "土家族", "彝族", "蒙古族", "藏族",
                "布依族", "侗族", "瑶族", "朝鲜族", "白族", "哈尼族", "哈萨克族", "黎族", "傣族", "畲族",
                "傈僳族", "仡佬族", "东乡族", "高山族", "拉祜族", "水族", "佤族", "纳西族", "羌族", "土族",
                "仫佬族", "锡伯族", "柯尔克孜族", "达斡尔族", "景颇族", "毛南族", "撒拉族", "布朗族", "塔吉克族",
                "阿昌族", "普米族", "鄂温克族", "怒族", "京族", "基诺族", "德昂族", "保安族", "俄罗斯族", "裕固族",
                "乌孜别克族", "门巴族", "鄂伦春族", "独龙族", "塔塔尔族", "赫哲族", "珞巴族");
            array_unshift($mzopt, "-----请选择-----");

            $admindzz = session("dzzid");
            if ($admindzz) {
                $this->assign("dzzinfo", M("dzz")->find($admindzz));
            }

            $this->assign("data", $data);
            $this->assign("dzzopt", $dzzopt);
            $this->assign("mzopt", $mzopt);
            $this->display();

        }
    }


    /**
     * 党组织管理
     */
    public function zqdw($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        $dzztype = I("dzztype", "全部");
        if ($dzztype != "全部") {
            $map["type"] = $dzztype;
        }
        if ($admindzz) {
            $map["id"] = $admindzz;
        }

        $map["ljz_dzz.status"] = 1;
        $model = M('dzz');
        $list = $model->where($map)->page($page, $r)->field('ljz_dzz.*,(select  count(*) from ljz_party_member where dzz=ljz_dzz.id) membercout')->select();

        foreach ($list as $k=>&$v){
            $v['content'] = preg_replace("/(\s|\&nbsp\;|　|\xc2\xa0)/","",strip_tags($v['content'],""));
        }

        $totalCount = $model->where($map)->count();

        foreach ($list as &$v) {
            $v['name_href'] = "<a href='" . U('dzzcy', array('dzz' => $v['id'])) . "' >" . $v['name'] . "</a>";
        }

        $dzztypeopt = array(array("id" => "全部", "value" => "全部"));
        $dzztypearr = M("dzz")->where(array("status" => array('egt',-1)))->field("type")->group("type")->select();
        foreach ($dzztypearr as $v1) {
            $dzztypeopt[] = array("id" => $v1["type"], "value" => $v1["type"]);
        }

        $builder = new AdminListBuilder();
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title("党组织管理");
        if (!$admindzz) {
            $builder->buttonNew(U('editDzz'))
                ->setStatusUrl(U('setDzzStatus'))
                ->buttonDelete()
                ->setSelectPostUrl(U("zqdw"))
                ->select("党组织类型", "dzztype", "select", "", "", "", $dzztypeopt);
        }
        $builder->keyId()->keyText("name_href", "组织名称")->keyText("membercout", "人数")->keyText("type", "组织类型")->keyText("content", "党委概况")
            ->keyDoActionEdit('Zzgl/editDzz?id=###')
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    /**
     * 新增或修改党组织
     */
    public function editDzz()
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $data['type'] = $data['type_wrap'];
            $DZZ = M('dzz');
            if ($data["id"]) {
                if ($DZZ->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($DZZ->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            $data = array();
            if ($is_edit) {
                $data = M('dzz')->where(array('id' => $id))->find();
                $data['type_wrap'] = $data['type'];
            }


            $dzztypeopt = array();
            $dzztypearr = M("dzz")->where(array("status" => array('egt',-1)))->field("type")->group("type")->select();
            foreach ($dzztypearr as $v1) {
                $dzztypeopt[$v1["type"]] = $v1["type"];
            }
            $builder = new AdminConfigBuilder;
            $builder->title($title . "党组织信息");
            $builder->keyId()
                ->keySelect("type_wrap", "类型", "", $dzztypeopt)
                ->keyText("name", "党组织名称")
                ->keyRichText("content", "党委概况")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }

    /**
     * 设置党组织状态
     */
    public function setDzzStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('dzz', $ids, $status);
    }


    /**
     * 组织生活会
     */
    public function zzshh($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        if($admindzz){
            $map["dzzid"] =$admindzz;
        }

        //读取列表
        $map["status"] = 1;
        $model = M('data_zzshh');
        $list = $model->where($map)->page($page, $r)->select();

        foreach ($list as $i => &$value) {
            $value['index'] = $i + ($page - 1) * 10 + 1;
        }

        $totalCount = $model->where($map)->count();

        $pager = new \Think\Page($totalCount, $r, $_REQUEST);
        $pager->setConfig('theme', '%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
        $paginationHtml = $pager->show();
        $this->assign('pagination', $paginationHtml);

        $this->assign("list", $list);

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $this->display();
    }


    public function zzshhDel()
    {
        $ids = I('id');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_zzshh', $ids, $status);
    }

    public function zzshhDtl()
    {
        $map['id'] = I('get.id');
        if (!$map['id']) {
            $this->error('无效id');
            exit;
        }

        $map['status'] = 1;
        $data = M('data_zzshh')->where($map)->find();
        $this->assign('data', $data);
        $this->display();
    }


    public function zzshhEdit()
    {
        $admindzz = session("dzzid");
        if (IS_POST) {
            $data = $_POST;
            $ZZSHH = M('data_zzshh');
            if($admindzz && $admindzz!=$data["dzzid"]){
                $this->error("您无权编辑此信息");
            }

            if ($data["id"]) {
                if ($ZZSHH->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($ZZSHH->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }
        } else {
            $id = I("get.id", 0,"intval");
            if ($id) {
                $data = M('data_zzshh')->find($id);
                if ($data['dzzid']) {
                    $dzzinfo = M('dzz')->find($data['dzzid']);
                    $data['dzztype'] = $dzzinfo['type'];
                    $data['dzzname'] = $dzzinfo['name'];
                }


                if ($data['people']) {
                    $map['id'] = array('in', explode(',', $data['people']));
                    $people = M('party_member')->where($map)->field('name,id')->select();
                    $this->assign("people", $people);
                }
            }
            if($admindzz){
                if($id){
                    if($admindzz != $data["dzzid"]){
                      $this->error("您无权查看此信息");
                    }
                }
                $dzzinfo2 =M('dzz')->find($admindzz);
                $this->assign("admindzz",$dzzinfo2);
                $data['dzztype'] = $dzzinfo2['type'];
                $data['dzzname'] = $dzzinfo2['name'];
            }
            $this->assign("data", $data);
            $dzztype = M("dzz")->field('type')->group('type')->select();
            $this->assign("dzztype", $dzztype);
            foreach ($dzztype as $v) {
                $dzzmap['type'] = $v['type'];
                $dzzname[$v['type']] = M("dzz")->where($dzzmap)->select();
            }
            if ($data['dzzid']) {
                $this->assign("dzzname", $dzzname[$data['dzztype']]);
            } else {
                $this->assign("dzzname", $dzzname[$dzztype[0]['type']]);
            }
            $this->assign("dzznamestr", json_encode($dzzname));

            $this->display();
        }
    }

    public function listPartyMember($key = '')
    {
        $map['name'] = array('like', "%$key%");
        $limit = I("limit", 0, "intval");
        if ($limit) {
            $people = M('party_member')->where($map)->limit($limit)->select();
        } else {
            $people = M('party_member')->where($map)->select();
        }

        $res['result'] = 1;
        $res['data'] = $people;
        echo json_encode($res);
        exit;
    }

    public function listMemberByDzzid($dzzid)
    {
        $map['dzz'] = $dzzid;
        $people = M('party_member')->where($map)->select();
        $res['result'] = 1;
        $res['data'] = $people;
        $pids = array();
        foreach ($people as $v) {
            $pids[] = $v["id"];
        }
        $res['pids'] = $pids;

        echo json_encode($res);
        exit;
    }

    public function wxmember($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");
        //读取列表
        $map["status"] = 1;

        $zt = I("zt",0,"intval");

        if($admindzz){
            switch ($zt) {
                case 0:
                    $map["_string"] = " dzz  = 0  or dzz = $admindzz";
                    break;
                case 1:
                    $map["pmid"] = array("exp", "is null");
                    $map["dzz"] = $admindzz;
                    break;
                case 2:
                    $map["pmid"] = array("gt", 0);
                    $map["dzz"] = $admindzz;;
                    break;
                case 3:
                    $map["pmid"] = array("exp", "is null");
                    $map["dzz"] = 0;
                    break;
            }
        }else {
            if($zt) {
                switch ($zt) {
                    case 1:
                        $map["pmid"] = array("exp", "is null");
                        $map["dzz"] = array("neq",0);
                        break;
                    case 2:
                        $map["pmid"] = array("gt", 0);
                        break;
                    case 3:
                        $map["pmid"] = array("exp", "is null");
                        $map["dzz"] = 0;
                        break;
                }
            }
        }

        $model = M('wxmember');
        $list = $model->where($map)->page($page, $r)->select();

//        foreach ($list as $i => &$value) {
//            $value['index'] = $i + ($page - 1) * 10 + 1;
//        }

        $totalCount = $model->where($map)->count();

//        $pager = new \Think\Page($totalCount, $r, $_REQUEST);
//        $pager->setConfig('theme', '%FIRST% %UP_PAGE% %LINK_PAGE% %DOWN_PAGE% %END% %HEADER%');
//        $paginationHtml = $pager->show();
//        $this->assign('pagination', $paginationHtml);
//        $this->assign("list", $list);
//        Cookie('__forward__', $_SERVER['REQUEST_URI']);
//        $this->display();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
            if ($v['dzz']) {
                $dzz = M('dzz')->where(array("id" => $v['dzz']))->find();
                $v['dzzname'] = $dzz["name"];
            }
            $v["bdstate"] = $v["pmid"] ? "已绑定" : "未绑定";
            if ($v["pmid"]) {
                $v["_hide"] = array("去绑定");
            } else {
                $v["_hide"] = array("解绑");
            }
        }
        unset($v);

        $ztopt = array(
            array("id"=>0,"value"=>"全部"),
            array("id"=>1,"value"=>"待绑定"),
            array("id"=>2,"value"=>"已绑定"),
            array("id"=>3,"value"=>"普通用户")
        );


        //显示页面
        $builder = new AdminListBuilder();
//        $builder->setSelectPostUrl(U("dzzcy"));
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('微信用户')
            ->setSelectPostUrl(U("wxmember"))
            ->select("状态", "zt", "select", "", "", "", $ztopt)
            ->keyId()
            ->keyImage('headimage', '微信头像', array("width" => 60, "height" => 60))
            ->keyText('nick', '微信昵称')
            ->keyText('sex_str', '性别')
            ->keyText("name", "真实姓名")
            ->keyText("mobile", "电话")
            ->keyText("addr", "地址")
            ->keyText('dzzname', "党组织")
            ->keyText('bdstate', "绑定状态")
            ->keyDoAction("Zzgl/cjhd?id=###", "查看报名活动")
//            ->keyDoAction("zzgl/wxbd?id=###", "去绑定")
//            ->keyDoAction("wxunbind?id=###", "解绑", "操作", array('class' => 'ajax-get'))
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function wxunbind($id)
    {
        $data["id"] = $id;
        $data["pmid"] = null;
        if (M("wxmember")->save($data) !== false) {
            $this->success("解绑成功");
        } else {
            $this->error(L('解绑失败'));
        }
    }

    /**
     * 微信绑定
     */
    public function wxbd($id)
    {
        if (IS_POST) {
            $model = M('wxmember');
            $data["id"] = $id;
            $data["pmid"] = $_POST["pmid"];
            if (!$data["pmid"]) {
                $this->error("请选择要绑定的党员");
            }
            $data["dzz"] = M("party_member")->getFieldById($data["pmid"],"dzz");
            if (!$data["dzz"]) {
                $this->error(L('_FAIL_UPDATE_')."，党组织不能为空");
            }
            if ($model->save($data) !== false) {
                $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
            } else {
                $this->error(L('_FAIL_UPDATE_'));
            }
        } else {
            $this->assign("data", M("wxmember")->find($id));
            $this->display();
        }
    }


    /**
     * 参加活动
     */
    public function cjhd($id)
    {

        $wxmember = M("wxmember")->where(array("id" => $id))->find();
        $map['openid'] = $wxmember['openid'];
        $list = M("data_hdbm")->where($map)->select();
        foreach ($list as $k => $v) {
            $info = M("data_hdyg")->where('id=' . $v['aid'])->find();
            $list[$k]['name'] = $info['name'];
            $list[$k]['date'] = $info['date'];
            $list[$k]['addr'] = $info['addr'];
            $list[$k]['count'] = $info['count'];
            $list[$k]['type'] = $info['type'];
            $list[$k]['content'] = $info['content'];
            if ($list[$k]['type'] == '1') $list[$k]['typename'] = '文体活动';
            if ($list[$k]['type'] == '2') $list[$k]['typename'] = '志愿公益';
            if ($list[$k]['type'] == '3') $list[$k]['typename'] = '群团活动';
            if ($list[$k]['type'] == '4') $list[$k]['typename'] = '书记带教';
        }
        $this->assign('user', $wxmember);
        $this->assign('list', $list);
        $this->display();
    }

    /**
     * 民主评议
     */
    public function mzpy($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        $dzzid = I("dzzid", 0, "intval");
        if ($dzzid) {
            $map["dzzid"] = $dzzid;
        }
        if($admindzz){
            $map["dzzid"] = $admindzz;
        }

        $map["status"] = 1;
        $year = I("year", 0, "intval");
        if (!$year) {
            $year = max(date("Y"), M("mzpy")->where($map)->max("year"));
        }
        if ($year) {
            $map["year"] = $year;
        }
        $_GET['year'] = $year;


        //读取列表
        $map["status"] = 1;
        $model = M('data_mzpy');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
            $v["dzzname"] = M("dzz")->getFieldById($v['dzzid'], "name");
        }
        unset($v);

        //所属党组织
        $dzzopt = M("dzz")->where(array("status" => 1))->order("type")->field("name,id")->select();
        $dzzidopt = array(array("id" => "0", "value" => "全部"));
        foreach ($dzzopt as $v) {
            $dzzidopt[] = array("id" => $v['id'], "value" => $v['name']);
        }
        unset($v);
        $years = M("data_mzpy")->where($map)->order("year")->field("year")->group("year")->select();
        $yearopt = array();
        foreach ($years as $v) {
            $yearopt[] = array("id" => $v['year'], "value" => $v['year'] . "年");
        }
        unset($v);
        //显示页面
        $builder = new AdminListBuilder();
//        $builder->setSelectPostUrl(U("dzzcy"));
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('民主评议')
            ->buttonNew(U("editmzpy"))
            ->setSelectPostUrl(U('Zzgl/mzpy'));
         if(!$admindzz){
             $builder->select("党组织", "dzzid", "select", "", "", "", $dzzidopt);
         }
            $builder->select("年份", "year", "select", "", "", "", $yearopt)
            ->setStatusUrl(U('setmzpystatus'))->buttonDelete()
            ->keyId()
            ->keyText('name', '姓名')
            ->keyText('sex_str', '性别')
            ->keyText("nation", "民族")
            ->keyText("state", "状态")
            ->keyText('dylx', "党员类型")
            ->keyText('pydate', "评议时间")
            ->keyText('suggest', "评议意见")
            ->keyText('dzzname', "所属党组织")
            ->keyText("year", "年份")
            ->keyDoActionEdit("editmzpy?id=###")
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function setmzpystatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_mzpy', $ids, $status);
    }


    public function editmzpy()
    {
        $admindzz = session("dzzid");
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $DZZ = M('data_mzpy');
            if ($data["id"]) {
                if ($DZZ->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($DZZ->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            $data = array();
            if ($is_edit) {
                $data = M('data_mzpy')->where(array('id' => $id))->find();
            }
            if($admindzz) {
                $dzzinfo = M("dzz")->find($admindzz);
                $data["dzzname"] = $dzzinfo["name"];
            }
//            $dzztypeopt = array();
//            $dzztypearr = M("dzz")->where(array("status" => 1))->field("type")->group("type")->select();
//            foreach ($dzztypearr as $v1) {
//                $dzztypeopt[$v1["type"]] = $v1["type"];
//            }

            //所属党组织
            $dzzopt = M("dzz")->where(array("status" => 1))->order("type")->field("name,id")->select();
            array_unshift($dzzopt, array("id" => "", "name" => "-----请选择-----"));
            $dzzopt = array_combine(array_column($dzzopt, "id"), array_column($dzzopt, "name"));

            $yearopt = array();
            for ($i = 2015; $i < 2031; $i++) {
                $yearopt[$i] = $i . "年";
            }

            $builder = new AdminConfigBuilder;
            $builder->title($title . "民主评议");
            $builder->keyId()
                ->keyText("name", "姓名");
                if($admindzz){
                    $builder->keyLabel("dzzname", "所属党组织");
                }else{
                    $builder->keySelect("dzzid", "所属党组织", "", $dzzopt);
                }
                $builder->keySelect("sex", "性别", "", array("1" => "男", "2" => "女"))
                ->keySelect("year", "年份", "", $yearopt)
                ->keyText("nation", "民族")
                ->keyText("birth", "出生年月")
                ->keyText("state", "人员状态")
                ->keyText("dylx", "党员类型")
                ->keyText("rddate", "入党年月")
                ->keyText("pydate", "评议时间")
                ->keyText("suggest", "评议意见")
                ->keyText("sszb", "所属支部")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }







    /**
     * 双报到
     */
    public function sbd($page = 1, $r = 10)
    {
        $admindzz = session("dzzid");

        $dzzid = I("dzz", 0, "intval");
        if ($dzzid) {
            $map["dzz"] = $dzzid;
        }
        if($admindzz){
            $map["dzz"] = $admindzz;
        }

        $sbdstate = I("sbdstate", 100, "intval");
        if($sbdstate!=100){
            $map["sbdstate"] = $sbdstate;
        }
        $_GET["sbdstate"] =$sbdstate;

        $map["status"] = 1;
        $map["sbd"] = 1;
        $model = M('party_member');
        $list = $model->where($map)->page($page, $r)->select();

        $totalCount = $model->where($map)->count();
        $sexmap = array("1" => "男", "2" => "女");
        $sbdstateopt = array("1" => "审核通过", "0" => "待审核","-1"=>"审核未通过");
        foreach ($list as &$v) {
            $v['sex_str'] = $sexmap[$v['sex']];
            $v["dzzname"] = M("dzz")->getFieldById($v['dzz'], "name");
            $v["sbdstate_str"] = $sbdstateopt[$v['sbdstate']];
        }
        unset($v);

        //所属党组织
        $dzzopt = M("dzz")->where(array("status" => 1))->order("type")->field("name,id")->select();
        $dzzidopt = array(array("id" => "0", "value" => "全部"));
        foreach ($dzzopt as $v) {
            $dzzidopt[] = array("id" => $v['id'], "value" => $v['name']);
        }
        unset($v);

        $sbdstateopt  = array(array("id"=>100,"value"=>"全部"),
            array("id"=>0,"value"=>"待审核"),
            array("id"=>1,"value"=>"审核通过"),
            array("id"=>-1,"value"=>"审核未通过"));


        //显示页面
        $builder = new AdminListBuilder();
//        $builder->setSelectPostUrl(U("dzzcy"));
        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder->title('双报到')
            ->buttonNew(U("editsbd"))
            ->setSelectPostUrl(U('Zzgl/sbd'));
        if(!$admindzz){
            $builder->select("党组织", "dzz", "select", "", "", "", $dzzidopt);
        }
        $builder->select("审核状态", "sbdstate", "select", "", "", "", $sbdstateopt);
        $builder->setStatusUrl(U('setsbdstatus'))->buttonDelete()
            ->ajaxButton(U("setsbdstate"),array("state"=>1),"审核通过")
            ->ajaxButton(U("setsbdstate"),array("state"=>-1),"审核不通过")
            ->keyId()
            ->keyText('name', '姓名')
            ->keyText('dzzname', '双报道党组织')
            ->keyText('sex_str', '性别')
            ->keyText("mz", "民族")
            ->keyText("birth", "出生年月")
            ->keyText("addr", "居住地址")
            ->keyText('gzdw', "工作单位")
            ->keyText('zw', "职务")
            ->keyText('tc', "特长")
            ->keyText('tel', "联系方式")
            ->keyText("bz", "备注")
            ->keyText("ydzz", "原党支部")
            ->keyText("sbdstate_str", "审核状态")
            ->keyDoActionEdit("editsbd?id=###")
            ->data($list)
            ->pagination($totalCount, $r)
            ->display();
    }

    public function setSbdstatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('party_member', $ids, $status);
    }

    public function setSbdstate()
    {
        $ids = I('ids');
        $state = I('get.state', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetFields('party_member', $ids, array("sbdstate"=>$state));
    }


    public function editsbd()
    {
        $admindzz = session("dzzid");
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;

            if($admindzz && !$data["dzz"]){
                $data["dzz"] = $admindzz;
            }

            $DZZ = M('party_member');
            if ($data["id"]) {
                if ($DZZ->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($DZZ->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            $data = array();
            if ($is_edit) {
                $data = M('party_member')->where(array('id' => $id))->find();
            }
            if($admindzz) {
                $dzzinfo = M("dzz")->find($admindzz);
                $data["dzzname"] = $dzzinfo["name"];
            }
//            $dzztypeopt = array();
//            $dzztypearr = M("dzz")->where(array("status" => 1))->field("type")->group("type")->select();
//            foreach ($dzztypearr as $v1) {
//                $dzztypeopt[$v1["type"]] = $v1["type"];
//            }

            //所属党组织
            $dzzopt = M("dzz")->where(array("status" => 1))->order("type")->field("name,id")->select();
            array_unshift($dzzopt, array("id" => "", "name" => "-----请选择-----"));
            $dzzopt = array_combine(array_column($dzzopt, "id"), array_column($dzzopt, "name"));


            $builder = new AdminConfigBuilder;
            $builder->title($title . "双报到");
            $builder->keyId()
                ->keyText("name", "姓名");
            if($admindzz){
                $builder->keyLabel("dzzname", "所属党组织");
            }else{
                $builder->keySelect("dzz", "所属党组织", "", $dzzopt);
            }
            $builder->keySelect("sex", "性别", "", array("1" => "男", "2" => "女"))
                ->keyText("mz", "民族")
                ->keyText("birth", "出生年月")
                ->keyText("addr", "居住地址")
                ->keyText('gzdw', "工作单位")
                ->keyText('zw', "职务")
                ->keyText('tc', "特长")
                ->keyText('tel', "联系方式")
                ->keyText("bz", "备注")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }












    public function regTest()
    {

        $dzz = M("dzz")->field("id,namestr,py1")->select();

//        $error = array();
//        foreach ($dzz as &$v){
//            $v["py1"] = pinyin($v["namestr"],true);
//
//             $res = M("dzz")->save($v);
//            if($res === false){
//                $error[] = $v['id'];
//            }
//        }
//        echo "失败的：";
//        dump($error);
        unset($v);

        foreach ($dzz as $v) {
            $ucenterMemberModel = UCenterMember();
            if (M("ucenter_member")->where(array("username" => $v["py1"]))->find()) {
                continue;
            }

            $uid = $ucenterMemberModel->register($v['py1'], $v['namestr'], "123321");
            if (0 < $uid) { //注册成功

            } else { //注册失败，显示错误信息
                echo $v["id"] . ":" . $this->showRegError($uid) . "\n";
            }
        }
    }

    /**
     * 获取用户注册错误信息
     * @param  integer $code 错误编码
     * @return string        错误信息
     */
    public function showRegError($code = 0)
    {
        switch ($code) {
            case -1:
                $error = L('') . modC('USERNAME_MIN_LENGTH', 2, 'USERCONFIG') . '-' . modC('USERNAME_MAX_LENGTH', 32, 'USERCONFIG') . L('_ERROR_LENGTH_2_') . L('_EXCLAMATION_');
                break;
            case -2:
                $error = L('_ERROR_USERNAME_FORBIDDEN_') . L('_EXCLAMATION_');
                break;
            case -3:
                $error = L('_ERROR_USERNAME_USED_') . L('_EXCLAMATION_');
                break;
            case -4:
                $error = L('_ERROR_LENGTH_PASSWORD_') . L('_EXCLAMATION_');
                break;
            case -5:
                $error = L('_ERROR_EMAIL_FORMAT_2_') . L('_EXCLAMATION_');
                break;
            case -6:
                $error = L('_ERROR_EMAIL_LENGTH_') . L('_EXCLAMATION_');
                break;
            case -7:
                $error = L('_ERROR_EMAIL_FORBIDDEN_') . L('_EXCLAMATION_');
                break;
            case -8:
                $error = L('_ERROR_EMAIL_USED_2_') . L('_EXCLAMATION_');
                break;
            case -9:
                $error = L('_ERROR_PHONE_FORMAT_2_') . L('_EXCLAMATION_');
                break;
            case -10:
                $error = L('_ERROR_FORBIDDEN_') . L('_EXCLAMATION_');
                break;
            case -11:
                $error = L('_ERROR_PHONE_USED_') . L('_EXCLAMATION_');
                break;
            case -20:
                $error = L('_ERROR_USERNAME_FORM_') . L('_EXCLAMATION_');
                break;
            case -30:
                $error = L('_ERROR_NICKNAME_USED_') . L('_EXCLAMATION_');
                break;
            case -31:
                $error = L('_ERROR_NICKNAME_FORBIDDEN_2_') . L('_EXCLAMATION_');
                break;
            case -32:
                $error = L('_ERROR_NICKNAME_FORM_') . L('_EXCLAMATION_');
                break;
            case -33:
                $error = L('_ERROR_LENGTH_NICKNAME_1_') . modC('NICKNAME_MIN_LENGTH', 2, 'USERCONFIG') . '-' . modC('NICKNAME_MAX_LENGTH', 32, 'USERCONFIG') . L('_ERROR_LENGTH_2_') . L('_EXCLAMATION_');;
                break;
            default:
                $error = L('_ERROR_UNKNOWN_');
        }
        return $error;
    }

    /**
     * 积分规则管理
     */
    public function jfgz($type = "1")
    {
        $map["status"] = 1;
        $map["jftype"] = $type;
        $model = M('data_jfsd');
        $list = $model->where($map)->select();

        $jftypeopt = array("1" => "基本分(50分)", "2" => "履职分（30分）", "3" => "奉献分(20分)", "4" => "加减分");

        Cookie('__forward__', $_SERVER['REQUEST_URI']);
        $builder = new AdminListBuilder();
        $builder->title($jftypeopt[$type])->buttonNew(U("editJfgz", array("jftype" => $type)))->setStatusUrl(U("setJfgzStatus"))->buttonDelete();
        $builder->keyId()->keyText("title", "名称")->keyText("content", "规则描述")->keyText("fen", "分值")
            ->keyDoActionEdit('Zzgl/editJfgz?id=###')
            ->data($list)
            ->display();
    }

    public function setJfgzStatus()
    {
        $ids = I('ids');
        $status = I('get.status', 0, 'intval');
        $builder = new AdminListBuilder();
        $builder->doSetStatus('data_jfsd', $ids, $status);
    }

    function editJfgz($jftype = "1")
    {
        $id = I('id', 0, 'intval');
        $is_edit = $id ? 1 : 0;
        $title = $is_edit ? "编辑" : "添加";
        if (IS_POST) {
            $data = $_POST;
            $DZZ = M('data_jfsd');
            if ($data["id"]) {
                if ($DZZ->save($data) !== false) {
                    $this->success(L('_SUCCESS_UPDATE_'), Cookie('__forward__'));
                } else {
                    $this->error(L('_FAIL_UPDATE_'));
                }
            } else {
                if ($DZZ->add($data) !== false) {
                    $this->success("添加成功", Cookie('__forward__'));
                } else {
                    $this->error("添加失败");
                }
            }

        } else {
            $data = array();
            $data["jftype"] = $jftype;
            if ($is_edit) {
                $data = M('data_jfsd')->where(array('id' => $id))->find();
            }
            $dzztypeopt = array("1" => "基本分", "2" => "履职分", "3" => "奉献分", "4" => "加减分");
            $builder = new AdminConfigBuilder;
            $builder->title($title . "积分规则");
            $builder->keyId()
                ->keySelect("jftype", "规则类型", "", $dzztypeopt)
                ->keyText("title", "名称")
                ->keyTextArea("content", "规则描述")
                ->keyText("fen", "分值")
                ->buttonSubmit()
                ->buttonBack()
                ->data($data)
                ->display();
        }
    }
    public function daoru()
    {
        $admindzz = session("dzzid");
        if(!$admindzz){
            $admindzz=0;
        }
        $this->assign("groupid",$admindzz);
        $this->display();
    }



    public function testiframe(){
        $this->display("testiframe");
    }

    public function toAct(){

     echo   "<script>window.location.href ='/leader/pages/activity.html'</script>";exit;
    }

    public function toCenter(){
        echo   "<script>window.location.href ='/leader/pages/center.html'</script>";exit;
    }

    public function toJifen(){
        echo   "<script>window.location.href ='/leader/pages/jifen.html'</script>";exit;
    }

    public function toDsj(){
        echo   "<script>window.location.href ='/leader/pages/dsj.html'</script>";exit;
    }

    public function toAct2(){

        echo   "<script>window.location.href ='/leader2/pages/activity.html'</script>";exit;
    }

    public function toCenter2(){
        echo   "<script>window.location.href ='/leader2/pages/center.html'</script>";exit;
    }

    public function toJifen2(){
        echo   "<script>window.location.href ='/leader2/pages/jifen.html'</script>";exit;
    }

    public function toDsj2(){
        echo   "<script>window.location.href ='/leader2/pages/dsj.html'</script>";exit;
    }

}
